### ISSUE TITLE
Ugly dotted rectagles when you click on it.

### ISSUE THREAD

**Issue by juliusPeters** [eskimoblood/jim-knopf#13]
Very nice and elegant knobs.
I am using Firefox on Ubuntu Linux 16. When I click on any of these knobs (at the demo page as well) a ugly dotted rectangle appears. This rectangle is normally a little wider than the knob area, sometime is shifted a little to the right, but always covers the area from the lower border of the knob up to the upper border of the Firefox window. As it always goes up to the top of the Firefox window, it can become quiet large and is very interfering with the rest of the page.
What is this and can it be removed.
Thanks for all your work.
Julius

**Comment by eskimoblood** [comment]
You can remove it using CSS `outline: none;` for the `div` that holds the `svg`

**Comment by juliusPeters** [comment]
This worked fine. Thank you. 
Actually I used outline-style:none; (just outline works as well) and did the correction in knop.js line 32. Later I will do it in the -min version as well. 
While searching for that div, I notice that there is a ";" missing just before the end of line 6.
Again thanks.
Julius
