### ISSUE TITLE
set initial value of knob

### ISSUE THREAD

**Issue by stahlnow** [eskimoblood/jim-knopf#7]
Hello, I need advice in how to set the initial value when creating a knob. Also a simple callback example would help me.

**Comment by HenningKlokkeraasen** [comment]
Seems like initial value is always set to

**Comment by eskimoblood** [comment]
Just set the value of the input HTML element before creating the knob

**Comment by eskimoblood** [comment]
Just set the value of the input HTML element before creating the knob

**Comment by HenningKlokkeraasen** [comment]
I'm not sure that will work since this seem to set it to something else:
this.value = input.value = settings.min + settings.range / 2;
