### ISSUE TITLE
mouse dragging in bootstrap 

### ISSUE THREAD

**Issue by TPei** [eskimoblood/jim-knopf#8]
when using knobs with bootstrap, as soon as a knob is inside a col with a size (col-md-12 etc.), the mouse dragging stops working. It doesn't matter how many layers down the DOM the knob is inside the col.

**Comment by eskimoblood** [comment]
Could please create an example on [jsbin](http://jsbin.com/) so I can check this. Thanks.

**Comment by TPei** [comment]
sure, here you go:
http://jsbin.com/wunejazoha/1/

**Comment by eskimoblood** [comment]
Ok, the problem is the use of `offsetTop` and `offsetLeft` to get the position of the knob container, this will fail if the container is inside a relative positioned container as bootstrap column. I will fix it by using `getBoundingClientRect`.

**Comment by TPei** [comment]
Hey, I still got this issue in Firefox. But strangely, only occasionally... Does that make any sense? Are there any known issues in Firefox?

**Comment by eskimoblood** [comment]
Does it relates to the scroll position?

**Comment by TPei** [comment]
oh, yeah, it does. Once I am scrolled completely to the top of the page it works flawlessly, if I'm not, it doesn't

**Comment by TPei** [comment]
Does that tell you anything? Ever experienced that "bug"?
